spring:
  application:
    name: gateway-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #是否使用service-id的小写，默认是大写
      routes:
        - id: gateway-nacos-provider
          uri: lb://gateway-nacos-provider #其中配置的lb://表示从注册中心获取服务，后面的gateway-nacos-provider表示目标服务在注册中心上的服务名
          predicates:
            - Path=/nacos/**
          filters:
            - StripPrefix=1
server:
  port: 8888

